Dog.class: Hunger.class Emotion.class Sleep.class Pet.class Dog.java
	javac Dog.java

Pet.class: Hunger.class Emotion.class Sleep.class Pet.java
	javac Pet.java

Hunger.class: Hunger.java
	javac Hunger.java

Emotion.class: Emotion.java
	javac Emotion.java

Sleep.class: Sleep.java
	javac Sleep.java

run: Dog.class
	java Dog

clean:
	rm *.class
